# Generated by Django 3.2 on 2022-01-02 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_auto_20220102_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, verbose_name='کد')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_information',
        ),
        migrations.DeleteModel(
            name='ProductInformation',
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_Code', to='product_module.productcode', verbose_name='کد محصول'),
        ),
    ]
