# Generated by Django 3.2 on 2022-01-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_auto_20220102_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_tags',
            field=models.ManyToManyField(to='product_module.ProductTag', verbose_name='برچسب'),
        ),
    ]
