# Generated by Django 3.2 on 2022-01-02 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0010_alter_product_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product_module.productcode', verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_tags',
            field=models.ManyToManyField(related_name='products', to='product_module.ProductTag', verbose_name='برچسب'),
        ),
    ]
