# Generated by Django 3.2 on 2022-01-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'لیست تماس با ما'},
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='messages',
            new_name='message',
        ),
    ]
