# Generated by Django 3.2 on 2022-02-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0004_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل\u200cها'},
        ),
    ]
